[toolchain]
channel = "stable"

[programs.devnet]
proofmesh_gate = "6hrtRLHSL3aKQifdz1prM1APBCRAz2XjghqxfNxBkJeV"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"